#!/usr/bin/env python3
import bwt
import random

alpha = ['A', 'C', 'G', 'T']
t = ['$'] + [random.choice(alpha) for x in range(10000)]
alphabet = alpha + ['$']

b = 5
print('OldRow, First, Checkpt, NewRow, SA, Checkpt, Reord')
fm = bwt.constructFM(t, b, alphabet)
bwt.insert(fm, b, alphabet, 1, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 5, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 10, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 50, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 100, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 500, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 1000, random.choice(alpha), timing=True)
bwt.insert(fm, b, alphabet, 5000, random.choice(alpha), timing=True)
print()
fm = bwt.constructFM(t, b, alphabet)
bwt.insert(fm, b, alphabet, 1, 'A', timing=True)
bwt.insert(fm, b, alphabet, 5, 'A', timing=True)
bwt.insert(fm, b, alphabet, 10, 'A', timing=True)
bwt.insert(fm, b, alphabet, 50, 'A', timing=True)
bwt.insert(fm, b, alphabet, 100, 'A', timing=True)
bwt.insert(fm, b, alphabet, 500, 'A', timing=True)
bwt.insert(fm, b, alphabet, 1000, 'A', timing=True)
bwt.insert(fm, b, alphabet, 5000, 'A', timing=True)
bwt.insert(fm, b, alphabet, 10000, 'A', timing=True)
print()
fm = bwt.constructFM(t, b, alphabet)
bwt.insert(fm, b, alphabet, 1, 'C', timing=True)
bwt.insert(fm, b, alphabet, 5, 'C', timing=True)
bwt.insert(fm, b, alphabet, 10, 'C', timing=True)
bwt.insert(fm, b, alphabet, 50, 'C', timing=True)
bwt.insert(fm, b, alphabet, 100, 'C', timing=True)
bwt.insert(fm, b, alphabet, 500, 'C', timing=True)
bwt.insert(fm, b, alphabet, 1000, 'C', timing=True)
bwt.insert(fm, b, alphabet, 5000, 'C', timing=True)
bwt.insert(fm, b, alphabet, 10000, 'C', timing=True)
print()
fm = bwt.constructFM(t, b, alphabet)
bwt.insert(fm, b, alphabet, 1, 'G', timing=True)
bwt.insert(fm, b, alphabet, 5, 'G', timing=True)
bwt.insert(fm, b, alphabet, 10, 'G', timing=True)
bwt.insert(fm, b, alphabet, 50, 'G', timing=True)
bwt.insert(fm, b, alphabet, 100, 'G', timing=True)
bwt.insert(fm, b, alphabet, 500, 'G', timing=True)
bwt.insert(fm, b, alphabet, 1000, 'G', timing=True)
bwt.insert(fm, b, alphabet, 5000, 'G', timing=True)
bwt.insert(fm, b, alphabet, 10000, 'G', timing=True)
print()
fm = bwt.constructFM(t, b, alphabet)
bwt.insert(fm, b, alphabet, 1, 'T', timing=True)
bwt.insert(fm, b, alphabet, 5, 'T', timing=True)
bwt.insert(fm, b, alphabet, 10, 'T', timing=True)
bwt.insert(fm, b, alphabet, 50, 'T', timing=True)
bwt.insert(fm, b, alphabet, 100, 'T', timing=True)
bwt.insert(fm, b, alphabet, 500, 'T', timing=True)
bwt.insert(fm, b, alphabet, 1000, 'T', timing=True)
bwt.insert(fm, b, alphabet, 5000, 'T', timing=True)
bwt.insert(fm, b, alphabet, 10000, 'T', timing=True)
